-- 1. 식사 기록을 저장하는 user_meals 테이블 생성
CREATE TABLE IF NOT EXISTS public.user_meals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    meal_type text NOT NULL,
    items jsonb NOT NULL,
    total_carbon numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. RLS(Row Level Security) 설정 (보안 정책)
-- 사용자가 로그인했을 때 본인의 식사 데이터만 읽고 쓰고 삭제할 수 있도록 설정합니다.
ALTER TABLE public.user_meals ENABLE ROW LEVEL SECURITY;

-- 2-1. 본인 데이터 조회(SELECT) 정책
CREATE POLICY "Users can view their own meals." 
ON public.user_meals 
FOR SELECT 
USING (auth.uid() = user_id);

-- 2-2. 데이터 추가(INSERT) Policies
CREATE POLICY "Users can insert their own meals." 
ON public.user_meals 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 2-3. 데이터 삭제(DELETE) Policies
CREATE POLICY "Users can delete their own meals." 
ON public.user_meals 
FOR DELETE 
USING (auth.uid() = user_id);

-- 3. 로그인 기록을 저장하는 user_login_logs 테이블 생성
CREATE TABLE IF NOT EXISTS public.user_login_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    email text NOT NULL,
    login_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-1. RLS(Row Level Security) 설정
ALTER TABLE public.user_login_logs ENABLE ROW LEVEL SECURITY;

-- 3-2. 본인 로그인 기록 조회(SELECT) 정책
CREATE POLICY "Users can view their own login logs." 
ON public.user_login_logs 
FOR SELECT 
USING (auth.uid() = user_id);

-- 3-3. 로그인 기록 추가(INSERT) 정책
CREATE POLICY "Users can insert their own login logs." 
ON public.user_login_logs 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 3-4. 회원가입 기록을 저장하는 user_signup_logs 테이블 생성
CREATE TABLE IF NOT EXISTS public.user_signup_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-5. RLS(Row Level Security) 설정
ALTER TABLE public.user_signup_logs ENABLE ROW LEVEL SECURITY;

-- 3-6. 본인 가입 로그 조회(SELECT) 정책
CREATE POLICY "Users can view their own signup logs." 
ON public.user_signup_logs 
FOR SELECT 
USING (auth.uid() = user_id);

-- 3-7. 가입 로그 추가(INSERT) 정책
CREATE POLICY "Users can insert their own signup logs." 
ON public.user_signup_logs 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);


-- 4. 탈퇴 기록을 저장하는 user_withdrawal_logs 테이블 생성
-- (탈퇴된 유저의 정보가 삭제되어도 보존되도록 auth.users 외래키 제약조건을 걸지 않습니다)
CREATE TABLE IF NOT EXISTS public.user_withdrawal_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    email text NOT NULL,
    deleted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4-1. RLS(Row Level Security) 설정 (일반 유저의 직접 조작 방지)
ALTER TABLE public.user_withdrawal_logs ENABLE ROW LEVEL SECURITY;

-- 5. 회원탈퇴 프로세스 DB 함수 정의 (RPC 함수)
-- delete_user() 함수 실행 시 탈퇴 로그 적재 후 유저 정보 및 식단 이력을 영구 삭제 처리합니다.
-- SECURITY DEFINER 권한으로 실행되어 RLS 정책을 우회하여 탈퇴 로그를 삽입하고 계정을 삭제합니다.
CREATE OR REPLACE FUNCTION delete_user()
RETURNS void AS $$
DECLARE
  v_email text;
  v_parts text[];
  v_local text;
  v_domain text;
  v_masked_local text;
BEGIN
  -- auth.users 테이블에서 탈퇴 유저의 이메일 조회
  SELECT email INTO v_email FROM auth.users WHERE id = auth.uid();
  
  -- 이메일 마스킹 처리 (예: abcde@example.com -> ab***@example.com)
  IF v_email IS NOT NULL AND POSITION('@' IN v_email) > 0 THEN
    v_parts := string_to_array(v_email, '@');
    v_local := v_parts[1];
    v_domain := v_parts[2];
    IF LENGTH(v_local) <= 2 THEN
      v_masked_local := RPAD(SUBSTRING(v_local FROM 1 FOR 1), LENGTH(v_local), '*');
    ELSE
      v_masked_local := SUBSTRING(v_local FROM 1 FOR 2) || REPEAT('*', LENGTH(v_local) - 2);
    END IF;
    v_email := v_masked_local || '@' || v_domain;
  ELSE
    v_email := 'unknown@email.com';
  END IF;
  
  -- 탈퇴 이력 테이블에 마스킹된 이메일 로그 추가
  INSERT INTO public.user_withdrawal_logs (user_id, email)
  VALUES (auth.uid(), v_email);

  -- 유저의 식사 이력 데이터 삭제
  DELETE FROM public.user_meals WHERE user_id = auth.uid();
  
  -- auth.users에서 유저 영구 제거
  DELETE FROM auth.users WHERE id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 6. pgcrypto 확장 활성화 (비밀번호 강제 해싱용)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 7. 비밀번호 힌트 질문 및 답변을 보관하는 user_password_hints 테이블 생성
CREATE TABLE IF NOT EXISTS public.user_password_hints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    email text UNIQUE NOT NULL,
    hint_question text NOT NULL,
    hint_answer text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7-1. RLS(Row Level Security) 설정
ALTER TABLE public.user_password_hints ENABLE ROW LEVEL SECURITY;

-- 7-2. 본인 힌트 정보 조회(SELECT) 및 추가(INSERT) 정책
CREATE POLICY "Users can view their own hints." 
ON public.user_password_hints FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own hints." 
ON public.user_password_hints FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 8. 이메일을 통해 힌트 질문을 반환하는 RPC 함수 정의
CREATE OR REPLACE FUNCTION get_user_hint_question(p_email text)
RETURNS text AS $$
DECLARE
  v_question text;
BEGIN
  SELECT hint_question INTO v_question 
  FROM public.user_password_hints 
  WHERE email = p_email 
  LIMIT 1;
  
  RETURN v_question;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. 힌트 답변을 확인하고 일치 시 비밀번호를 갱신하는 RPC 함수 정의
CREATE OR REPLACE FUNCTION verify_hint_and_reset_password(p_email text, p_answer text, p_new_password text)
RETURNS boolean AS $$
DECLARE
  v_real_answer text;
  v_user_id uuid;
BEGIN
  -- 이메일에 해당하는 실제 힌트 답변과 유저 ID 조회
  SELECT hint_answer, user_id INTO v_real_answer, v_user_id
  FROM public.user_password_hints
  WHERE email = p_email
  LIMIT 1;
  
  -- 답변 일치 여부 검사 (공백 제거 및 소문자 기준 대조)
  IF v_real_answer IS NOT NULL AND LOWER(TRIM(v_real_answer)) = LOWER(TRIM(p_answer)) THEN
    -- auth.users의 encrypted_password를 bcrypt 해시로 강제 갱신
    UPDATE auth.users 
    SET encrypted_password = crypt(p_new_password, gen_salt('bf'))
    WHERE id = v_user_id;
    
    RETURN true;
  ELSE
    RETURN false;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;



